variables:
  GIT_CLEAN_FLAGS: -ffdx -e node_modules/ -e .m2/repository/
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository/

stages:
  - dependencies
  - compile
  - test
  - build

npm:
  image: node:latest
  stage: dependencies
  script: npm install
  cache:
    key: npm
    paths:
      - node_modules/
    policy: push
  only:
    changes:
      - package.json
      - package-lock.json

maven:
  image: maven:3.6.3-jdk-8
  stage: dependencies
  script:
    - mvn dependency:resolve
    - ls -la
  cache:
    key: maven
    paths:
      - .m2/repository/
    policy: push
  only:
    changes:
      - pom.xml

compile-angular:
  image: node:latest
  stage: compile
  script:
    - ls -la
    - node_modules/.bin/ng build --prod
  artifacts:
    expire_in: 12 hours
    paths:
      - src/server/resources/static/
  cache:
    key: npm
    policy: pull
  dependencies:
    - npm

compile-kotlin:
  image: maven:3.6.3-jdk-8
  stage: compile
  before_script:
    - chmod a+x ./mvnw
  script:
    - ./mvnw compile
  artifacts:
    expire_in: 12 hours
    paths:
      - target/classes
      - target/generated-sources
      - target/maven-status
  cache:
    key: maven
    policy: pull-push

test-angular:
  image: node:latest
  stage: test
  script:
    - ls

test-kotlin:
  image: maven:3.6.3-jdk-8
  services:
    - postgres:12.2-alpine
  variables:
    POSTGRES_DB: iasa-projectview-test
    POSTGRES_USER: runner
    POSTGRES_HOST_AUTH_METHOD: trust
  stage: test
  before_script:
    - chmod a+x ./mvnw
  script:
    - ./mvnw \
      -Dspring.profile.active=test \
      -Dspring.datasource.url="jdbc:postgresql://postgres:5432/${POSTGRES_DB}" \
      -Dspring.datasource.username=${POSTGRES_USER} \
      -Dspring.datasource.initialization-mode=always \
      test
  allow_failure: true

package:
  image: maven:3.6.3-jdk-8
  stage: build
  script:
    - chmod a+x ./mvnw
    - ./mvnw install -Dmaven.test.skip=true
    - ls -la
  dependencies:
    - compile-kotlin
    - compile-angular
  artifacts:
    expire_in: 12 hours
    paths:
      - target/projectview-0.0.1.jar
  cache:
    key: maven
    policy: pull

